# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: cm-agent-pool

variables:
- group: OptiSuite

steps:
- script: test
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo $(enable_sonar)
  displayName: 'Run a multi-line script'
